import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>jrwjjrw</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="relative">
        <div className="bg-hero-section bg-no-repeat h-screen bg-center bg-cover">
          <video autoPlay loop muted className="absolute inset-0 object-cover h-screen xl:h-auto">
            <source
              src="homepage/robovice-banner.mp4"
              type="video/mp4"
            />
          </video>
          <div className="absolute inset-0">
            <div className="sm:text-5xl text-4xl font-thin sm:my-56 my-32 mx-16 text-center text-white">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores cum nobis reprehenderit sequi explicabo at.
            </div>
          </div>
        </div>
        </div>
        </main>
        </>
  )
}

